version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'direct'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'styled-components'
    groups:
      storybook:
        patterns:
          - '*storybook*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
